- app/views/application/your-choices/index.html
- app/views/application/your-choices/routes.js
> MVP-459 OCJ content iterated after design review workshop

- app/views/start-page.html
> MVP-460 content updated using design workshop outputs

- app/views/application/reporting-crime-not-reported/index.html
> MVP-431 content changes following design workshop

- app/views/index.html
This PR adds links to archives for sprints 5, 6 and 7 and stops links opening in new windows
> Added links to releases

- app/routes-content.js
- app/views/application/who-is-making-the-application/error.html
- app/views/application/who-is-making-the-application/routes.js
> MVP-216 create error message for who is applying

- app/routes-content.js
- app/views/application/email-address/error.html
- app/views/application/over-18/error.html
- app/views/application/over-18/routes.js
file created, content routes and routes.js updated. screenshot of content below
> MVP-296 over 18 error message

- app/views/application/reporting-crime-not-reported/index.html
content change suggested by P.O. change "crime" to "injury"
> MVP-431 content change

- app/views/application/bridge/index.html
> MVP-415 Interstitial page content updated

- app/routes-content.js
- app/views/application/what-is-relationship/index.html
> MVP-417 Change content in response to PLADS feedback

- app/routes-content.js
- app/views/application/incident-reported/error.html
- app/views/application/incident-reported/routes.js
> MVP-226 Error state for was crime reported question

- app/routes-content.js
- app/views/application/crime-reference/error.html
- app/views/application/crime-reference/routes.js
> MVP-238 Error state created for Crime reference number Q

- app/routes-content.js
- app/views/application/crime-reported-date/error-blank.html
- app/views/application/crime-reported-date/error-format.html
- app/views/application/crime-reported-date/error-incomplete.html
- app/views/application/crime-reported-date/error-past.html
- app/views/application/crime-reported-date/routes.js
Screenshots below.  Incomplete and Format errors use same content
> MVP-228 Error states for reporting date

- app/routes-content.js
- app/views/application/reporting-delay/index.html
- components/radios/template.njk
Screen redesigned.  Demo below.
> MVP-442 New design for delayed reporting screen

- app/routes-content.js
- app/views/application/check-your-answers-page/includes/_other_compensation.html
- app/views/application/compensation/index.html
- app/views/application/compensation/routes.js
- app/views/application/do-you-know-offender/routes.js
- app/views/application/phone-number/routes.js
- app/views/application/what-is-relationship/routes.js
- lib/govuk_template.html
- New design for comp page created using radio buttons and conditionally revealing text fields.
- Screen moved in the prototype.  Will now appear when either "Do you know the offender" is answered No or immediately after "Contact with offender"., and will immediately precede the "Enter your name" screen.
- Check your answer screen content updated to ensure that all permutations of "Yes/Yes, but.../No" responses are displayed.
Demo of screen to follow
> MVP-418 Update to compensation screen, routing and check your answers results

- app/routes-content.js
- app/views/application/impact-on-you/index.html
- app/views/application/your-choices/index.html
OCJ screens refined using UR insights from,user testing last week and pair writing with PLADS
> MVP-496 OCJ pages content updated

- app/routes-content.js
- app/views/application/name-other/error.html
- app/views/application/name-other/routes.js
> MVP-276 Error state when no other names are entered

- app/views/application/impact-on-you/index.html
- app/views/application/your-choices/index.html
Changes suggested as a result of feedback at Decision forum with EMB:
Before you continue
•	Change upsetting to Difficult
•	Remove first sentence
Select the option…
•	Use “Any compensation we pay acknowledges…”
•	Remove “something” from DMI.  Reintroduce “substantial adverse effect”
•	Change 11 to 12 months
•	Reword last sentence
•	Switch order of loss of foetus and std
> MVP-496 Content changes to B4U continue and OCJ screens

- app/views/application/confirmation-page/index.html
Content changes and corrected a font colour error in previous iteration (black to white in the panel)
> MVP-473 Content changes

- app/routes-content.js
- app/views/application/application-delay/index.html
Design of page changed in response to EMB and User feedback.
- Checkboxes with conditionally reveal fields used
- Police advise and court advice options merged into one "advised to wait"
- heading changed to make it less similar to the other delay question
> MVP-518 Application delay

- app/views/application/confirmation-page/index.html
Having moved the email address I'm wondering if we need to tell users what to do if they need to make us aware of a change to something that they have told us. Like their email address or home address. 
What do you think @johnkane1 @Julieallan @samgroves19
> Moved the position of the email to make it more prominent

- app/routes-content.js
- app/views/application/reporting-delay/index.html
Reverts CriminalInjuriesCompensationAuthority/apply-for-compensation-prototype#148
We need to make further changes:
- keep heading the same as previous version
- move the question to further on in the flow
> Revert "MVP-519 Reporting delay reasons"

- app/views/application/application-submitted-email/index.html
- app/views/application/confirmation-page/index.html
Notify email content created in prototype.  Link on confirmation page "Check your inbox" will take them to the screen below
> MVP-494 Notify email content

- app/routes-content.js
- app/views/application/address-non-uk/error.html
- app/views/application/address-non-uk/routes.js
Error state content created as per BDD requirements. Screenshot below
> MVP-282 Error state for non UK address

- app/views/application/your-choices/index.html
Content changes made in response to UR feedback.  Not yet ready to be merged as code needs tidied up for reveal text
> MVP-538 OCJ Content changes

- app/routes-content.js
- app/views/application/address-manually/error-postcode.html
- app/views/application/address-manually/routes.js
Error state for when user enters a postcode that does not conform to expected pattern
> MVP-395 Postcode error for manual address

- app/routes-content.js
- app/views/application/what-is-relationship/index.html
UR insights suggest that user need to know why we are asking this question.  Screenshot below
> MVP-581 Offender contact hint text added

- app/routes-content.js
- app/views/application/what-is-relationship/error.html
- app/views/application/what-is-relationship/routes.js
Error state created for when user does not enter any details or does not select the checkbox.  No error would be produced if either the text box is completed or the checkbox selected.  Screenshot below
> MVP-262 Error state for offender contact screen

- app/routes-content.js
- app/views/application/do-you-know-offender/error.html
- app/views/application/do-you-know-offender/routes.js
Screenshot of error state below for when user does not select Yes or No.
> MVP-254 Error state for Do you know offender screen

- app/routes-content.js
- app/views/application/offender-name/error.html
- app/views/application/offender-name/routes.js
Error state created for offender name screen for when no data is entered in the field.  Screenshot below.
> MVP-256 Error state for offender name screen

- app/views/application/impact-on-you/index.html
- app/views/application/your-choices/error.html
- app/views/application/your-choices/index.html
- app/views/start-page.html
Start page design updated to:
- Place the “Northern Ireland” link at the end of the sentence as per hyperlink good practice
- change the URL and content for Victim and Witness Information link
I also updated the Victim and Witness Information content and URL on other pages for consistency - “Before you continue” and “Select the option…” pages.
> MVP-214 Start page design

- app/views/application/check-your-answers-page/index.html
Content changes requested by EMB/Senior stakeholders implemented.  Screenshot below.
> MVP-602 Consent content changes

- app/routes-content.js
- app/views/application/previous-applications/error.html
- app/views/application/previous-applications/routes.js
Based on BDDs, Error state content created for when a user does not select a radio button.  Screenshot below.
> MVP-247 Error state for previous application screen

- app/routes-content.js
- app/routes.js
- app/views/application/england-forces/index.html
- app/views/application/england-forces/routes.js
- app/views/application/england-location/index.html
- app/views/application/england-location/routes.js
- app/views/application/incident-location/index.html
- app/views/application/incident-location/routes.js
- app/views/application/scotland-forces/index.html
- app/views/application/scotland-forces/routes.js
- app/views/application/scotland-location/index.html
- app/views/application/scotland-location/routes.js
- app/views/application/somewhere-else/index.html
- app/views/application/somewhere-else/routes.js
- app/views/application/wales-forces/index.html
- app/views/application/wales-forces/routes.js
- app/views/application/wales-location/index.html
- app/views/application/wales-location/routes.js
Redesigned screens for:
- incident location
- England/Scotland/Wales location details
- England force drop down selection
- Scotland/Wales force radio buttons
- Somewhere else screen for users to contact us.  There were 122 cases last year (0.2% of caseload)
Screenshots and error messaging to follow
> MVP-544 Police force MVP concept adopted

- app/views/application/Error-internal-server-error/index.html
- app/views/application/Error-page-not-found/index.html
Page not found/404 error page created in accordance with GDS design system pattern https://design-system.service.gov.uk/patterns/page-not-found-pages/
> MVP-507 Page not found - 404 error - created

- app/views/application/incident-date/error-before-reported.html
- app/views/application/incident-date/error-incomplete.html
- app/views/application/incident-date/error-past.html
- app/views/application/incident-date/index.html
- app/views/application/incident-reported/error.html
- app/views/application/incident-reported/index.html
- app/views/application/period-of-abuse-end/error-after-started.html
- app/views/application/period-of-abuse-end/error-before-reported.html
- app/views/application/period-of-abuse-end/error-incomplete.html
- app/views/application/period-of-abuse-end/error-past.html
- app/views/application/period-of-abuse-end/index.html
- app/views/application/period-of-abuse-start/error-before-reported.html
- app/views/application/period-of-abuse-start/error-incomplete.html
- app/views/application/period-of-abuse-start/error-past.html
- app/views/application/period-of-abuse-start/index.html
Hyperlink to Police 101 number removed from incident reported and date screens at request of EMB/Senior stakeholders during review meeting.
New screenshots for content and error states attached below
> MVP-621 Removing 101 hyperlink from incident questions

- app/routes-content.js
- app/routes.js
- app/views/concepts/comp/compensation/error-no-radio.html
- app/views/concepts/comp/compensation/error-no-why-not.html
- app/views/concepts/comp/compensation/index.html
- app/views/concepts/comp/compensation/routes.js
- app/views/concepts/comp/other-compensation/error-amount.html
- app/views/concepts/comp/other-compensation/error-source.html
- app/views/concepts/comp/other-compensation/index.html
- app/views/concepts/comp/other-compensation/routes.js
- app/views/index.html
For presentation to the team for feedback and questions raised.
> Compensation concept added

- app/routes-content.js
- app/routes.js
- app/views/concepts/timeout/timed-out/index.html
- app/views/concepts/timeout/timed-out/routes.js
- app/views/index.html
Page the user goes to when they have timed out after 30 minutes. For content review
> Timeout page added

- app/routes-content.js
- app/views/concepts/comp/other-compensation/index.html
For team discussion on whether this question is needed or not and best way to ask it.
> Added in "when will you be notified of a decision" 

- app/views/concepts/PB-research/email.html
- app/views/concepts/PB-research/index.html
- app/views/index.html
content created. further work required on:
- a link for user to click
- content that gathers the users name and preferred mode of contact
> PB research concept added

- app/views/index.html
New tab for UR testing prototypes
> Tidy up and new tab

- app/routes-content.js
- app/views/application/impact-on-you/index.html
- app/views/application/your-choices/error.html
- app/views/application/your-choices/index.html
- app/views/start-page.html
Link to help and support for residents of Scotland inserted in Start, Before you conteinue and Select an Option screens. https://www.mygov.scot/victim-witness-support/
Further work needed to correct missing error content on Select an option screen
> MVP-705 Insert gov.scot link

- app/views/concepts/guidance/application_submitted.html
Added in screenshot to AD Guidance
> Screenshot fixed - yay

- app/views/concepts/guidance/application_submitted.html
- app/views/concepts/guidance/includes/navigation.html
- app/views/concepts/guidance/index.html
Adding start button, A-Z and start at beginning links
> Small updates for presenting

- app/views/application/check-your-answers-page/includes/_your_details.html
- app/views/application/your-choices/index.html
- app/views/application/your-choices/routes.js
Small content amends:
- Changed question for Your choices page - and pulled in the "option 1: Sexual assault or abuse" answer
- Have you ever been know by any other _names_ not _name_
> CYA content fixes

- app/views/concepts/confirmation-page/index.html
- app/views/concepts/consent/index.html
- app/views/concepts/transition-OCJ/index.html
- app/views/index.html
New content for the concent up front as well as small tweaks to the transition and app submitted page
> Content updates

- app/views/application/impact-on-you/index.html
- app/views/application/your-choices/index.html
- app/views/concepts/support/impact-on-you.html
- app/views/concepts/support/start-page.html
- app/views/concepts/support/your-choices.html
- app/views/index.html
- app/views/start-page.html
Help & support content changed to mirror that of new design in SRR concept.  Pages affected are:
Start page
Before you continue
Select the option that applies to you
Screenshot of content below
> MVP-830 Help and support content changes

- app/views/concepts/gender/index.html
- app/views/concepts/gender/question.html
- app/views/index.html
Optional question added.
No need for error message if optional.
Business may want this as mandatory. In which case we should add 'Prefer not to say option'.
Escalating this issue.
> MVP 659 gender sex question

- app/routes.js
- app/views/concepts/police-force-V3/country/index.html
- app/views/concepts/police-force-V3/country/routes.js
- app/views/concepts/police-force-V3/crime-reference/error.html
- app/views/concepts/police-force-V3/crime-reference/index.html
- app/views/concepts/police-force-V3/crime-reference/routes.js
- app/views/concepts/police-force-V3/do-you-know-offender/index.html
- app/views/concepts/police-force-V3/do-you-know-offender/routes.js
- app/views/concepts/police-force-V3/england-forces/error.html
- app/views/concepts/police-force-V3/england-forces/index.html
- app/views/concepts/police-force-V3/england-forces/routes.js
- app/views/concepts/police-force-V3/incident-date/index.html
- app/views/concepts/police-force-V3/incident-date/routes.js
- app/views/concepts/police-force-V3/index.html
- app/views/concepts/police-force-V3/location/index.html
- app/views/concepts/police-force-V3/location/routes.js
- app/views/concepts/police-force-V3/routes.js
- app/views/concepts/police-force-V3/scotland-forces/error.html
- app/views/concepts/police-force-V3/scotland-forces/index.html
- app/views/concepts/police-force-V3/scotland-forces/routes.js
- app/views/concepts/police-force-V3/single-or-multiple-incidents/index.html
- app/views/concepts/police-force-V3/single-or-multiple-incidents/routes.js
- app/views/concepts/police-force-V3/somewhere-else/index.html
- app/views/concepts/police-force-V3/somewhere-else/routes.js
- app/views/concepts/police-force-V3/wales-forces/error.html
- app/views/concepts/police-force-V3/wales-forces/index.html
- app/views/concepts/police-force-V3/wales-forces/routes.js
- app/views/index.html
Hi guys,
So I think this might be a better solution. Its the police force concept 2 link in the concepts section...
So what I've done is directly after we ask when it was reported to the police, we ask where its being investigated (country) and then the force depending on what they choose. The journey then resumes as normal till location where I've removed the country questions and it only asks location then resumes... Hope that makes sense. You should be able to get it from the link. 
This change would just be an update to the route and some content tweaks so much easier for the devs to implement and means we are not adding/ or removing pages. Just rearranging a little.
I toyed with the idea of asking country on the location page?
@johnkane1 for the title of the country page - this was …
> MVP 681 police force

- app/routes-content.js
- app/routes.js
- app/views/application/gender/error.html
- app/views/application/gender/index.html
- app/views/application/gender/routes.js
- app/views/application/name-other/routes.js
- app/views/index.html
Link isnt working - coming back to it
> Added gender to main MVP

- app/views/concepts/guidance/eligibility-triage.html
- app/views/concepts/guidance/includes/navigation.html
- app/views/concepts/guidance/send-invitation-email.html
- app/views/concepts/guidance/start-page.html
I have changed the content on the Navigation menu and moved the link down to the correct alphabetic place in the list.  I will need some help from @maxinedivers to update the screenshot depicting the new content.
> MVP-870 AD guidance update

- app/views/concepts/tabbed-decision-letter/index.html
- app/views/index.html
Content copied from a stale branch. To be added to concepts list on prototype front page
> tabbed decision letter concept

- app/views/start-page.html
Private beta start page previously updated in response to feedback from GDS senior content designer.
This version has had content re-written in response to feedback from senior stakeholders including CICA CEO and Policy and Legal Heads of department.
> PB start page content update

- app/routes-content.js
- app/views/application/compensation/index.html
- app/views/application/other-compensation/index.html
2 page edited... moved who you have claimed from field in to the previous page under the the conditional yes radio
> Changes to the other compensation - 2 pages edited

- app/routes-content.js
- app/routes.js
- app/views/concepts/compensation/error-no-radio.html
- app/views/concepts/compensation/error-no-why-not.html
- app/views/concepts/compensation/index.html
- app/views/concepts/other-compensation/error-amount.html
- app/views/concepts/other-compensation/error-radios.html
- app/views/concepts/other-compensation/error-when.html
- app/views/concepts/other-compensation/error-who.html
- app/views/concepts/other-compensation/index.html
- app/views/index.html
> 2 new compensation pages put in to concepts folders

- app/routes-content.js
- app/views/application/compensation/index.html
- app/views/application/other-compensation/index.html
Reverts CriminalInjuriesCompensationAuthority/apply-for-compensation-prototype#262
> Revert "Changes to the other compensation - 2 pages edited"

- app/views/application/consent/index.html
- app/views/concepts/guidance/application-guidance.html
This change is to add an email address to the consent page.
> Added email address to consent page

- app/views/application/_3-3rd-party-reps/_1-adult/_1-rep-details/email-address/index.html
- app/views/application/_3-3rd-party-reps/_1-adult/_1-rep-details/email-address/routes.js
- app/views/application/_3-3rd-party-reps/_1-adult/_1-rep-details/phone-number/index.html
- app/views/application/_3-3rd-party-reps/_1-adult/_10-end/check-your-answers-page/includes/_1_rep_details.html
- app/views/application/_3-3rd-party-reps/_2-minors/_1-rep-details/email-address/index.html
- app/views/application/_3-3rd-party-reps/_2-minors/_1-rep-details/email-address/routes.js
- app/views/application/_3-3rd-party-reps/_2-minors/_1-rep-details/phone-number/index.html
- app/views/application/_3-3rd-party-reps/_2-minors/_10-end/check-your-answers-page/includes/_1_rep_details.html
- app/views/application/_3-3rd-party-reps/_2-minors/_10-end/confirmation-page/index.html
Merging latest updates with master
> Reps journey proto
