app/views/application/transition/index.html
Feedback from Ops that users may not understand the term beta.  A more descriptive title provided
=> Mvp 441 Transition page

app/views/application/incident-reported/index.html
Reveal detail added to screen to provide help for users who may not know if the crime was reported or not.  Created in response to feedback from EMB review workshop.  The "Police" link takes them user to Police 101 web page
=> MVP-467 Content added for users who do not know if crime was reported

app/routes-content.js, app/views/application/do-you-know-offender/index.html, app/views/application/offender-name/index.html
Moved and refined the offender name hint text from the first question of the series to the next one.
screenshots below
=> MVP-515 Move hint text from 1st to 2nd page of offender name series

app/views/application/address/error-blank-postcode.html, app/views/application/address/error-invalid-postcode.html, app/views/application/address/routes.js
2 error screens created for
- no postcode entered
- invalid/incomplete postcode entered
Content also refined - removed reveal so that manual address and non-UK links persist on screen.  Wording of links and "find" button also refined in line with other gov.uk examples.
=> 2 Error states and content changes for address postcode lookup

app/routes-content.js, app/views/application/phone-number/error.html, app/views/application/phone-number/routes.js
GDS guidance on telephone number error formats consulted - https://design-system.service.gov.uk/patterns/telephone-numbers/#error-messages
Error state created which will cover scenarios when:
field is left blank
an incorrect format is used
Awaiting BDD to see if we need to add further error states
=> MVP-526 Error state for phone number

app/views/application/incident-reported/index.html, app/views/start-page.html
Content re when and where changed in response to UR insights
hyperlinks updated to make the new screen appear in the same window rather than a new one to aid user navigation
additional guidance content provided in before you start section to link users to police website if they do not have all of the information mentioned in the bullets.
=> MVP-536 Start page content changes

app/views/application/impact-on-you/index.html, app/views/application/incident-date/error-before-reported.html, app/views/application/incident-date/error-incomplete.html, app/views/application/incident-date/error-past.html, app/views/application/incident-date/index.html, app/views/application/incident-reported/error.html, app/views/application/incident-reported/index.html, app/views/application/period-of-abuse-end/error-after-started.html, app/views/application/period-of-abuse-end/error-before-reported.html, app/views/application/period-of-abuse-end/error-incomplete.html, app/views/application/period-of-abuse-end/error-past.html, app/views/application/period-of-abuse-end/index.html, app/views/application/period-of-abuse-start/error-before-reported.html, app/views/application/period-of-abuse-start/error-incomplete.html, app/views/application/period-of-abuse-start/error-past.html, app/views/application/period-of-abuse-start/index.html, app/views/application/your-choices/index.html, app/views/start-page.html
Content for help guidance updated on:
* Start page
* Before you continue
* Select an option (OCJ)
* Was crime reported
* When did it happen
* When did it start
* When did it stop
And all associated error states.  All content checked for consistency.  Screenshots below
=> MVP-539 Help and support reveals

app/routes-content.js
Hint content changed to mirror that contained in notify email for consistency.  Also reduces any anxiety users may have about being contacted unnecessarily.  Screenshot below
=> MVP-582 change phone number hint text

app/views/application/application-submitted-email/index.html, app/views/application/confirmation-page/index.html
Latest EMB review meeting, senior stakeholders requested that we be more explicit about the need for users to immediately tell us about changes to their address, email and phone number.  The justification for this is that it is the biggest source of data breaches.
Screenshots of revised content attached below
=> MVP-603 Change in contact details content

app/routes-content.js, app/views/application/reporting-delay/error-checkboxes.html, app/views/application/reporting-delay/error-explain.html, app/views/application/reporting-delay/routes.js
Based on BDD error states created for when user:
1) doesnt select a checkbox option
2) doesnt enter any text in the explanation field
Screenshots below
=> MVP-251 Error states for reporting delay screen

app/routes-content.js, app/views/application/application-delay/error-checkboxes.html, app/views/application/application-delay/error-explain.html, app/views/application/application-delay/routes.js
Based on BDDs error states created for when the user:
1) doesnt select a checkbox
2) doesnt enter any text in explanationfield
screenshots below
=> MVP-444 Error state content for application delay screen

app/views/concepts/police-service/index.html, app/views/concepts/police-service/routes.js, app/views/index.html
I've done a tiny bit of tidying up by adding tabs: one for the current prototypes, one for notifications so decisions letters to go here @johnkane1 and one for the archive. It's fairly self explanatory but I thought it might be best to have the main MVP prototype thats going into private beta (PB) at the forefront and a space for concepts whilst we await the PB build. Let me know what you think @johnkane1, @Julieallan. Can discuss a bit more with you John tomorrow ;)
https://apply-for-compensation--pr-193.herokuapp.com/
=> New prototype starting page design adding concepts and archive tabs

app/routes-content.js, app/views/concepts/comp/other-compensation/index.html
Content changes made as discussed with @maxinedivers 
have commented out code relating to the conditionally revealing date boxes for a No answer on other comp screen.  Need further evidence to support the claimed business need for this.
=> content changes, date fields commented out of No answer

app/routes-content.js, app/views/concepts/comp/other-compensation/index.html
Hint text updated to cover both sets of circumstances, consistent with previous page (applied for , or received)
Removed hint text for amount, added in word "award" as per request from EMB
Changed "no" question, updated hint text to explain user can enter an approx date or dont know, made field larger to accommodate this and for style purposes
=> updated content on other comp concept

app/views/start-page.html
Updated link on start page to connect to the new relevant place guidance created in CICA guidance pages.
=> Start page link to relevant place guidance

app/views/start-page.html
Added a new line of content under the Before you start heading telling users that they need an email to use the MVP service.
=> MVP-730 email content

app/routes-content.js, app/routes.js, app/views/application/transition-OCJ-option-2/index.html, app/views/application/transition-OCJ-option-2/routes.js, app/views/application/your-choices/routes.js
PB users selecting option 2 on the OCJ screen will be redirected to the OAS service.  We need a more descriptive transition page to explain exactly why they are being redirected and reassure that they have done nothing wrong.  Support is available via phone to CSC or other 3rd part organisations (if user isnt signposted by them)
Demo of how it works below
=> MVP-693 OCJ option 2 redirect content

app/views/application/application-submitted-email/index.html, app/views/application/confirmation-page/index.html
We need to tell users that their decision letter will be posted to them, as we do not yet have an end to end digital journey in place.
Attached is screenshot of "Application submitted" page content for review.  We would mirror this in the Notify email that is sent to users.
=> MVP-731 Posting decision letter

app/views/application/confirmation-page/index.html, app/views/application/consent/index.html, app/views/application/reporting-crime-not-reported/index.html
@Julieallan @maxinedivers 
I reviewed the prototype content and identified 3 anomolies:
- an extra 'the' in the Your consent section of PB Consent
- 'can not' on the ineligiblity screen that needed changed to 'cannot'
- 3rd bullet on confirmation screen did not reflect recent change re posting the decision letter
all changes effected by this pull request
=> Content updates

app/views/application/application-submitted-email/index.html
Notify email content updated to include an invitation to user feedback survey.  This is a replication of the content in the Notify template, for use in prototype testing.  Screenshot below
=> MVP-785 Notify email survey content

app/views/index.html
New pull request sorry - original comment:
Would like to get your thoughts on this concept @Julieallan @johnkane1
The idea is that the user will go to google and the back button will be disabled. Thats the bit I was focussing on but think we could add the contact and support info here too so that its on every screen - what you think? Maybe even on pages such as police force or CRN we can add a bit of copy to say if you are unsure you can contact the police on 101 etc....?
Trying to keep this section as small and unobtrusive as possible though.
I've used a secondary button here that isn't in the design system but was one I used at DWP and looks like GDS are working on new secondary and tertiary buttons.
Also if we go ahead with this and test it in PB then MOJ would like to put it into …
=> Instant support 

app/config.js, app/views/start-page.html
This iteration has been designed in response to the following feedback from GDS:
- On GOV.UK, we don’t use ‘we’ or ‘us’ on mainstream content, ie in ‘To complete the application we ask for the:’ This would be more like... ‘To apply, you’ll need:’
- Layout and wording of the contact info in ‘Other ways to apply’ would appear as a content block (like the one on Universal Credit how to claim page). You can find the Govspeak mark up for ‘Contacts’ here
- use meaningful links that make sense when read out of context and are action focused (for accessibility). For example:
- ‘Contact the police’ needs something explaining in what context you’d do this in the link text
- ‘There’s a different website if you live in [Scotland]’ - ‘Scotland’ read aloud by a screenreader won’t make a lot of sense, …
=> MVP-855 Private Beta start page content

app/views/application/impact-on-you/index.html, app/views/application/your-choices/error.html, app/views/application/your-choices/index.html
Help and support content on "Before you continue" and "Select an option" screens updated to be consistent with the Start page, which was redesigned in response to GDS feedback.  This should provide more context about the links to users of screen readers.
Screenshots below
=> MVP-874 Help and support content
